services:
  - type: web
    name: xml-to-excel-converter
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: GOOGLE_DRIVE_CLIENT_ID
        sync: false
      - key: GOOGLE_DRIVE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_DRIVE_REDIRECT_URI
        sync: false 